# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.8'

# Define services
services:  
  ###################
  #    MONITORING   #
  ###################

  # ZipKin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: "no"
    container_name: odoru_zipkin
    networks:
      - backend
  
  # Prometheus
  prometheus:
    # Lancement service Prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: "no" 
    container_name: odoru_prometheus
    networks: 
      - backend

  #################
  #   DATABASE    #
  #################

  # Database ServiceUtilisateur (Mysql)
  mysql-utilisateur:
    image: mysql:latest
    ports:
      - "3308:3306"
    restart: always
    container_name: odoru_mysql_utilisateur
    environment:
      MYSQL_DATABASE: utilisateur
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - backutilisateur

  # Database ServiceBadge (Mysql)
  mysql-badge:
    image: mysql:latest
    ports:
      - "3309:3306"
    restart: always
    container_name: odoru_mysql_badge
    environment:
      MYSQL_DATABASE: badge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - backbadge

  # Database ServiceCours (Mongo)
  mongo-cours:
    image: mongo
    ports:
      - "27017:27017" # host is first, container is second.
    restart: always
    container_name: odoru_mongo_cours
    #volumes:
    #  - db-data-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: odoru_mongo_cours
    networks:
      - backcours

  # Database ServiceCompetition (Mongo)
  mongo-competition:
    image: mongo
    ports:
      - "27018:27017" # host is first, container is second.
    restart: always
    container_name: odoru_mongo_competition
    #volumes:
    #  - db-data-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: odoru_mongo_competition
    networks:
      - backcompetitions

# Networks to be created to facilitate communication between containers
networks:
  backend:
  backutilisateur:
  backcours:
  backcompetitions:
  backbadge: